// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ShopOnlineAPI.Migrations
{
    [DbContext(typeof(ShopOnlineDbContext))]
    [Migration("20230128232634_initialcreate")]
    partial class initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopOnline_API.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Productid")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ShopOnline_API.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("ShopOnline_API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ImageURL = "/Images/Beauty/Beauty1.png",
                            Price = 100m,
                            ProductDescription = "A kit provided by Glossier, containing skin care, hair care and makeup products",
                            ProductName = "Glossier - Beauty Kit",
                            Quantity = 100
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ImageURL = "/Images/Beauty/Beauty2.png",
                            Price = 50m,
                            ProductDescription = "A kit provided by Curology, containing skin care products",
                            ProductName = "Curology - Skin Care Kit",
                            Quantity = 45
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ImageURL = "/Images/Beauty/Beauty3.png",
                            Price = 20m,
                            ProductDescription = "A kit provided by Curology, containing skin care products",
                            ProductName = "Cocooil - Organic Coconut Oil",
                            Quantity = 30
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            ImageURL = "/Images/Beauty/Beauty4.png",
                            Price = 50m,
                            ProductDescription = "A kit provided by Schwarzkopf, containing skin care and hair care products",
                            ProductName = "Schwarzkopf - Hair Care and Skin Care Kit",
                            Quantity = 60
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            ImageURL = "/Images/Beauty/Beauty5.png",
                            Price = 30m,
                            ProductDescription = "Skin Care Kit, containing skin care and hair care products",
                            ProductName = "Skin Care Kit",
                            Quantity = 85
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            ImageURL = "/Images/Electronic/Electronics1.png",
                            Price = 100m,
                            ProductDescription = "Air Pods - in-ear wireless headphones",
                            ProductName = "Air Pods",
                            Quantity = 120
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            ImageURL = "/Images/Electronic/Electronics2.png",
                            Price = 40m,
                            ProductDescription = "On-ear Golden Headphones - these headphones are not wireless",
                            ProductName = "On-ear Golden Headphones",
                            Quantity = 200
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            ImageURL = "/Images/Electronic/Electronics3.png",
                            Price = 40m,
                            ProductDescription = "On-ear Black Headphones - these headphones are not wireless",
                            ProductName = "On-ear Black Headphones",
                            Quantity = 300
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            ImageURL = "/Images/Electronic/Electronic4.png",
                            Price = 600m,
                            ProductDescription = "Sennheiser Digital Camera - High quality digital camera provided by Sennheiser - includes tripod",
                            ProductName = "Sennheiser Digital Camera with Tripod",
                            Quantity = 20
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            ImageURL = "/Images/Electronic/Electronic5.png",
                            Price = 500m,
                            ProductDescription = "Canon Digital Camera - High quality digital camera provided by Canon",
                            ProductName = "Canon Digital Camera",
                            Quantity = 15
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            ImageURL = "/Images/Electronic/technology6.png",
                            Price = 100m,
                            ProductDescription = "Gameboy - Provided by Nintendo",
                            ProductName = "Nintendo Gameboy",
                            Quantity = 60
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            ImageURL = "/Images/Furniture/Furniture1.png",
                            Price = 50m,
                            ProductDescription = "Very comfortable black leather office chair",
                            ProductName = "Black Leather Office Chair",
                            Quantity = 212
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            ImageURL = "/Images/Furniture/Furniture2.png",
                            Price = 50m,
                            ProductDescription = "Very comfortable pink leather office chair",
                            ProductName = "Pink Leather Office Chair",
                            Quantity = 112
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            ImageURL = "/Images/Furniture/Furniture3.png",
                            Price = 70m,
                            ProductDescription = "Very comfortable lounge chair",
                            ProductName = "Lounge Chair",
                            Quantity = 90
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            ImageURL = "/Images/Furniture/Furniture4.png",
                            Price = 120m,
                            ProductDescription = "Very comfortable Silver lounge chair",
                            ProductName = "Silver Lounge Chair",
                            Quantity = 95
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            ImageURL = "/Images/Furniture/Furniture6.png",
                            Price = 15m,
                            ProductDescription = "White and blue Porcelain Table Lamp",
                            ProductName = "Porcelain Table Lamp",
                            Quantity = 100
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            ImageURL = "/Images/Furniture/Furniture7.png",
                            Price = 20m,
                            ProductDescription = "Office Table Lamp",
                            ProductName = "Office Table Lamp",
                            Quantity = 73
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            ImageURL = "/Images/Shoes/Shoes1.png",
                            Price = 100m,
                            ProductDescription = "Comfortable Puma Sneakers in most sizes",
                            ProductName = "Puma Sneakers",
                            Quantity = 50
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            ImageURL = "/Images/Shoes/Shoes2.png",
                            Price = 150m,
                            ProductDescription = "Colorful trainsers - available in most sizes",
                            ProductName = "Colorful Trainers",
                            Quantity = 60
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            ImageURL = "/Images/Shoes/Shoes3.png",
                            Price = 200m,
                            ProductDescription = "Blue Nike Trainers - available in most sizes",
                            ProductName = "Blue Nike Trainers",
                            Quantity = 70
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            ImageURL = "/Images/Shoes/Shoes4.png",
                            Price = 120m,
                            ProductDescription = "Colorful Hummel Trainers - available in most sizes",
                            ProductName = "Colorful Hummel Trainers",
                            Quantity = 120
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            ImageURL = "/Images/Shoes/Shoes5.png",
                            Price = 200m,
                            ProductDescription = "Red Nike Trainers - available in most sizes",
                            ProductName = "Red Nike Trainers",
                            Quantity = 100
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            ImageURL = "/Images/Shoes/Shoes6.png",
                            Price = 50m,
                            ProductDescription = "Birkenstock Sandles - available in most sizes",
                            ProductName = "Birkenstock Sandles",
                            Quantity = 150
                        });
                });

            modelBuilder.Entity("ShopOnline_API.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Beauty"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Furniture"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Electronics"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Shoes"
                        });
                });

            modelBuilder.Entity("ShopOnline_API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserName = "Bob"
                        },
                        new
                        {
                            Id = 2,
                            UserName = "Sarah"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
